variable "name" {}

variable "resource_group_name" {}

variable "location" {}

variable "app_service_plan_id" {}

variable "app_settings" {}

variable "container_name" {}

variable "log_analytics_workspace_id" {
  description = "(Optional) The ID of the Log Analytics Workspace which the OMS Agent should send data to."
  default     = null
}

variable "diagnostics_map" {
  description = "(Optional) Storage Account and Event Hub data for the AKS diagnostics"
  default = {
    diags_sa = null
    eh_id    = ""
    eh_name  = null
  }
}

variable "diagnostics_logs_map" {
  description = "(Optional) Send the logs generated by AKS master node to diagnostics"
  default = {
    log = [
      #["Category name",  "Diagnostics Enabled", "Retention Enabled", Retention period] 
      ["AppServiceHTTPLogs", true, true, 30],
      ["AppServiceConsoleLogs", true, true, 30],
      ["AppServiceAppLogs", true, true, 30],
      ["AppServiceFileAuditLogs", true, true, 30],
      ["AppServiceAuditLogs", true, true, 30]
    ]
    metric = [
      ["AllMetrics", true, true, 30],
    ]
  }
}

variable "tags" {
  description = "(Required) Map of tags for the deployment"
}
