public_portal_asg_resource_group_name="rg_cmt-21090009_nsgasg"

public_portal_forward_proxy_vm_instance_count = 1
public_portal_forward_proxy_vm_size="Standard_DS3_v2"
public_portal_forward_proxy_with_lb_sku="Standard"
public_portal_forward_proxy_name="publicportal"
public_portal_forward_proxy_vm_image_publisher="cloud-infrastructure-services"
public_portal_forward_proxy_vm_image_offer="squid-proxy"
public_portal_forward_proxy_vm_image_sku="squid-proxy"
public_portal_forward_proxy_vm_image_version="0.0.5"

public_portal_forward_proxy_vm_marketplace_name="squid-proxy"
public_portal_forward_proxy_vm_marketplace_publisher="cloud-infrastructure-services"
public_portal_forward_proxy_vm_marketplace_product="squid-proxy"

public_portal_forward_proxy_with_lb_rules_probe_port="443"
public_portal_forward_proxy_with_lb_rules_probe_protocol="Tcp"
public_portal_forward_proxy_with_lb_rules_lb_port="80"
public_portal_forward_proxy_with_lb_rules_backend_port="80"
public_portal_forward_proxy_with_lb_rules_load_distribution="Default"
public_portal_forward_proxy_with_lb_rules_idle_timeout_in_minutes="4"
public_portal_forward_proxy_vm_resource_group_name="rg_ort_public_portal_forward_proxy"
public_portal_forward_proxy_with_lb_public_ip_address_id=""
public_portal_forward_proxy_with_lb_static_ip=""

public_portal_forward_proxy_vm_admin_username="admin123"
public_portal_forward_proxy_vm_admin_password="irasgcc@12345"

public_portal_forward_proxy_vm_disable_password_authentication="true"
public_portal_forward_proxy_vm_os_type="linux"



